from turtle import *
t=Turtle() # creating obejct of turtle class
t.speed(1)  # help('turtle.speed')
t.shape('turtle') #help('turtle.shape')
t.hideturtle()
t.pencolor('green')
t.fillcolor('yellow')
t.pensize(5)
t.fillcolor('orange')
t.begin_fill()
t.forward(100)
# t.left(90)
# t.fd(100)
# t.left(90)
# t.fd(100)
# t.left(90)
# t.fd(100)
for i in range(3):
    t.left(90)
    t.fd(100)
t.end_fill()
t.penup()   #t.pu()
t.forward(100)
t.pendown()  #t.pd()
t.forward(100)
for i in range(3):
    t.left(90)
    t.fd(100)
done()